flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired



class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flaskblog/main/routes.py
from flask import render_template, request, Blueprint
from flaskblog.models import Post

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/home')
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.posted_date.desc()).paginate(per_page=5, page=page)
    return render_template('home.html', posts=posts)


@main.route('/about')
def about():
    return render_template('about.html', title='About page')

flaskblog/posts/routes.py
from flask import Blueprint
from flaskblog.models import Post
from flask import render_template, url_for, request, flash, redirect, abort
from flaskblog import db
from flaskblog.posts.forms import PostForm
from flask_login import current_user, login_required

posts = Blueprint('posts', __name__)


@posts.route('/new_post', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            post = Post(title=form.title.data, content=form.content.data, author=current_user)
            db.session.add(post)
            db.session.commit()
            flash("New post has been successfully created!", 'success')
            return redirect(url_for("main.home"))
    return render_template('newpost.html', title='New post', form=form, legend="New post")


@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', post=post, title=post.title)


@posts.route('/post/<int:post_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author.username != current_user.username:
        abort(403)
    form = PostForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            post.title = form.title.data
            post.content = form.content.data
            db.session.commit()
            flash("Post has been successfully edited!", 'success')
            return redirect(url_for("posts.post", post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('edit_post.html', title='Edit post', form=form, legend="Edit post")


@posts.route('/post/<int:post_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author.username != current_user.username:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import Blueprint
import os
from flaskblog.models import User, Post
from flask import render_template, url_for, request, flash, redirect, current_app
from flaskblog import bcrypt, db
from flaskblog.users.forms import RegisterForm, LoginForm, UpdateAccoutForm, RequestResetForm, ResetPasswordForm
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog.users.utils import save_file, send_request_mail


users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegisterForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            user = User(username=form.username.data, password=hashed_password, email=form.email.data)
            db.session.add(user)
            db.session.commit()
            flash(f'Account has been successfully created! Now, you can log in.', 'success')
            return redirect(url_for('main.home'))

    return render_template('register.html', title='Registration', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(email=form.email.data).first()
            if user and bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user, remember=form.remember_me.data)
                next_page = request.args.get('next')
                return redirect(url_for('main.home')) if not next_page else redirect(next_page)
            else:
                flash('Login unsuccessful, please check e-mail and password', 'failed')
    return render_template('login.html', title='Log in', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccoutForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            if form.picture.data:
                path = os.path.join(current_app.root_path, 'static/profile_pictures', current_user.img)
                os.remove(path)
                picture = save_file(form.picture.data)
                current_user.img = picture
            current_user.username = form.username.data
            current_user.email = form.email.data
            db.session.commit()
            flash("Your account has been successfully changed", 'success')
            return redirect('account')
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename=f'profile_pictures/{current_user.img}')
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route('/user/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first()
    posts = Post.query.filter_by(user_id=user.id).order_by(Post.posted_date.desc()).paginate(per_page=5, page=page)
    return render_template('user_posts.html', posts=posts)


@users.route('/request_reset', methods=['GET', 'POST'])
def request_reset():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            email = form.email.data
            if User.query.filter_by(email=email).first():
                send_request_mail(User.query.filter_by(email=email).first())
                flash("Check an email and follow the instruction to reset a password", 'success')
                return redirect(url_for("users.login"))
    return render_template('request.html', form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token=token)
    print(user)
    if user is None:
        flash('That is an invalid or expired token', 'failed')
        return redirect(url_for('users.request_reset'))
    form = ResetPasswordForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            hased_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            user.password = hased_password
            db.session.commit()
            flash('Your password has been updated! You are now able to log in', 'success')
            return redirect(url_for('main.login'))
    return render_template('reset_password.html', form=form)

flaskblog/templates/about.html
{% extends 'layout.html' %}
{% block content %}
    <h1> About page!</h1>
{% endblock content %}

flaskblog/templates/account.html
{% extends 'layout.html' %}
{% block content %}
    <div style="background-color: #E0E5EA;">
        <div class="metadata" id="account_info">
            <img class="profile_picture" alt="Profile picture" src="{{ image_file }}">
            <div>
                <h2>{{ current_user.username}}</h2>
                <p style="color: slategray; font-size: 12px;">{{ current_user.email }}</p>
            </div>
        </div>
        <form method="POST" action="" class="form" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset>
            <legend>Change account settings</legend>
            <div class="form_item">
                {{ form.username.label(class="form_item_label")}}
                {% if form.username.errors %}
                    {{ form.username(class="form_item_input bad_input")}}
                    {% for error in form.username.errors%}
                        <span class="bad_input_text">{{ error }}</span>
                    {% endfor %}
                {% else %}
                    {{ form.username(class="form_item_input")}}
                {% endif %}
            </div>
            <div class="form_item">
                {{ form.email.label(class="form_item_label")}}
                {% if form.email.errors %}
                    {{ form.email(class="form_item_input bad_input")}}
                    {% for error in form.email.errors%}
                        <span class="bad_input_text">{{ error }}</span>
                    {% endfor %}
                {% else %}
                    {{ form.email(class="form_item_input")}}
                {% endif %}
            </div>
            <div class="form_item">
                {{ form.picture.label()}}
                {{ form.picture(class = "")}}
                 {% if form.picture.errors %}
                    {% for error in form.picture.errors%}
                        <br><span class="bad_input_text">{{ error }}</span>
                    {% endfor %}
                 {% endif %}
            </div>
            <div class="form_item">
                {{ form.submit(class="form_item_input submit")}}
            </div>
        </fieldset>
        </form>
    </div>
{% endblock %}

flaskblog/templates/edit_post.html
{% extends 'layout.html' %}
{% block content %}
    <form method="POST" action="" class="form">
        {{ form.hidden_tag() }}
        <fieldset>
            <legend>{{ legend }}</legend>
            <div class="form_item">
                {{ form.title.label(class="form_item_label")}}
                {% if form.title.errors %}
                    {{ form.title(class="form_item_input bad_input")}}
                    {% for error in form.title.errors%}
                        <span class="bad_input_text">{{ error }}</span>
                    {% endfor %}
                {% else %}
                    {{ form.title(class="form_item_input")}}
                {% endif %}
            </div>

            <div class="form_item ">
                {{ form.content.label(class="form_item_label ")}}
                {% if form.content.errors %}
                    {{ form.content(class="form_item_input bad_input text_area")}}
                    {% for error in form.content.errors%}
                        <span class="bad_input_text">{{ error }}</span>
                    {% endfor %}
                {% else %}
                    {{ form.content(class="form_item_input text_area")}}
                {% endif %}
            </div>

            <div class="form_item">
                {{ form.submit(class="form_item_input submit")}}
            </div>
        </fieldset>
    </form>
{% endblock %}

flaskblog/templates/home.html
{% extends 'layout.html' %}
{% block content %}
    {% for post in posts.items %}
        <div class="post">
            <a class="name" href="{{ url_for('users.user_posts', username=post.author.username)}}"><img src="{{ url_for('static', filename="profile_pictures/" + post.author.img)}}" alt="Posts author image." class="article_img"></a>
            <div class="content">
                <div class="metadata">
                    <p><a class="name" href="{{ url_for('users.user_posts', username=post.author.username)}}">{{ post.author.username}}</a></p>
                    <p class="date">{{post.posted_date.strftime("%a %m %Y")}}</p>
                </div>
                <h2><a href="{{url_for('posts.post', post_id = post.id)}}">{{post.title}}</a></h2>
                <p>{{post.content}}</p>
            </div>
        </div>
    {% endfor %}
    <div class="pagination">
    {%- for page in posts.iter_pages(left_edge=1,right_edge=1, left_current=1, right_current=2) %}
        {% if page != None %}
            {% if page == posts.page %}
                <a href="{{ url_for("main.home", page=page) }}" class="pagination_item active" >{{ page }}</a>
            {% else %}
                <a href="{{ url_for("main.home", page=page) }}" class="pagination_item" >{{ page }}</a>
            {% endif %}
        {% else %}
            <a class="pagination_item" >...</a>
        {% endif %}
    {% endfor %}
    </div>
{% endblock content%}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Flask blog</title>
    {% endif %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" x>
    <script src="https://kit.fontawesome.com/6c2c37fab8.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <div id="logo"><a href="{{ url_for("main.home") }}">Flask blog</a></div>
        <div class="header nav">
            <a href="{{ url_for("main.home") }}">Home</a>
            <a href="{{ url_for("main.about") }}">About</a>
        </div>
        <div class="header auth">
            {% if current_user.is_authenticated %}
                <a href="{{url_for("posts.new_post")}}">New post</a>
                <a href="{{url_for("users.account")}}">Account</a>
                <a href="{{url_for("users.logout")}}">Log out</a>
            {% else %}
                <a href="{{url_for("users.register")}}">Register</a>
                <a href="{{url_for("users.login")}}">Log in</a>
            {% endif %}
        </div>
    </header>
    <main>
        <div class="container">
             {%with messages = get_flashed_messages(with_categories=True) %}
                {% if messages %}
                    {% for category, message  in messages %}
                        <div class="flash {{ category }}">
                            <p>{{ message }}</p>
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}
            {% endblock %}
        </div>
        <div class="sidebar">
            <h3>Our Sidebar</h3>
            <ul><p>Choose needed option</p>
                <li><a href="">Latest Posts</a></li>
                <li><a href="">Announcements</a></li>
                <li><a href="">Calendars</a></li>
                <li><a href="">...</a></li>
            </ul>
        </div>
    </main>
    <footer>
        <a href="{{ url_for("main.home") }}">Home</a>
        <a href="{{ url_for("main.about") }}">About</a>
         {% if current_user.is_authenticated %}
             <a href="{{url_for("posts.new_post")}}">New post</a>
            <a href="{{url_for("users.account")}}">Account</a>
            <a href="{{url_for("users.logout")}}">Log out</a>
         {% else %}
            <a href="{{url_for("users.register")}}">Register</a>
            <a href="{{url_for("users.login")}}">Log in</a>
         {% endif%}
    </footer>
</body>
</html>

flaskblog/templates/login.html
{% extends 'layout.html' %}
{% block content %}
    <form method="POST" action="" class="form">
        {{ form.hidden_tag() }}
        <fieldset>
            <legend>Log in</legend>
            <div class="form_item">
                {{ form.email.label(class="form_item_label")}}
                {% if form.email.errors %}
                    {{ form.email(class="form_item_input bad_input")}}
                    {% for error in form.email.errors%}
                        <span class="bad_input_text">{{ error }}</span>
                    {% endfor %}
                {% else %}
                    {{ form.email(class="form_item_input")}}
                {% endif %}
            </div>

            <div class="form_item">
                {{ form.password.label(class="form_item_label")}}
                {% if form.password.errors %}
                    {{ form.password(class="form_item_input bad_input")}}
                    {% for error in form.password.errors%}
                        <span class="bad_input_text">{{ error }}</span>
                    {% endfor %}
                {% else %}
                    {{ form.password(class="form_item_input")}}
                {% endif %}
            </div>

            <div class="form_item">
                {{ form.submit(class="form_item_input submit")}}
            </div>
        </fieldset>
    </form>
    <div class="hint">
        <span>Don't have an account?</span>
        <a href="{{url_for("users.login")}}"> Sign up </a>
    </div>
     <div class="hint">
        <span>Did you forget a password?</span>
        <a href="{{url_for("users.request_reset")}}"> Reset password </a>
    </div>
{% endblock %}

flaskblog/templates/newpost.html
{% extends 'layout.html' %}
{% block content %}
    <form method="POST" action="" class="form">
        {{ form.hidden_tag() }}
        <fieldset>
            <legend>{{ legend }}</legend>
            <div class="form_item">
                {{ form.title.label(class="form_item_label")}}
                {% if form.title.errors %}
                    {{ form.title(class="form_item_input bad_input")}}
                    {% for error in form.title.errors%}
                        <span class="bad_input_text">{{ error }}</span>
                    {% endfor %}
                {% else %}
                    {{ form.title(class="form_item_input")}}
                {% endif %}
            </div>

            <div class="form_item ">
                {{ form.content.label(class="form_item_label ")}}
                {% if form.content.errors %}
                    {{ form.content(class="form_item_input bad_input text_area")}}
                    {% for error in form.content.errors%}
                        <span class="bad_input_text">{{ error }}</span>
                    {% endfor %}
                {% else %}
                    {{ form.content(class="form_item_input text_area")}}
                {% endif %}
            </div>

            <div class="form_item">
                {{ form.submit(class="form_item_input submit")}}
            </div>
        </fieldset>
    </form>
{% endblock %}

flaskblog/templates/post.html
{% extends 'layout.html' %}
{% block content %}
    <div class="post">
        <a class="name" href="{{ url_for('users.user_posts', username=post.author.username)}}"><img src="{{ url_for('static', filename="profile_pictures/" + post.author.img)}}"
                                                                    alt="Posts author image." class="article_img"></a>
        <div class="content">
            <div class="metadata" style="justify-content: space-between">
                <div class="flex_row">
                    <p><a class="name" href="{{ url_for('users.user_posts', username=post.author.username)}}">{{ post.author.username}}</a></p>
                    <p class="date">{{post.posted_date.strftime("%a %m %Y")}}</p>
                </div>
                {% if post.author.username == current_user.username%}
                    <div class="flex_row">
                        <p><a class="name" href="{{url_for('posts.edit_post', post_id = post.id)}}"><i class="fas fa-edit"></i> Edit</a></p>
                        <p class="name"><a class="name" id="delete" href="{{url_for('posts.delete_post', post_id = post.id)}}"><i class="fas fa-trash-alt"></i> Delete</a></p>
                    </div>
                {% endif %}
            </div>
            <h2><a href="{{url_for('posts.post', post_id = post.id)}}">{{post.title}}</a></h2>
            <p>{{post.content}}</p>
        </div>
    </div>
{% endblock content%}

flaskblog/templates/register.html
{% extends 'layout.html' %}
{% block content %}
    <form method="POST" action="" class="form">
        {{ form.hidden_tag() }}
        <fieldset>
            <legend>Sign up</legend>
            <div class="form_item">
                {{ form.username.label(class="form_item_label")}}
                {% if form.username.errors %}
                    {{ form.username(class="form_item_input bad_input")}}
                    {% for error in form.username.errors%}
                        <span class="bad_input_text">{{ error }}</span>
                    {% endfor %}
                {% else %}
                    {{ form.username(class="form_item_input")}}
                {% endif %}
            </div>
            <div class="form_item">
                {{ form.email.label(class="form_item_label")}}
                {% if form.email.errors %}
                    {{ form.email(class="form_item_input bad_input")}}
                    {% for error in form.email.errors%}
                        <span class="bad_input_text">{{ error }}</span>
                    {% endfor %}
                {% else %}
                    {{ form.email(class="form_item_input")}}
                {% endif %}
            </div>
            <div class="form_item">
                {{ form.password.label(class="form_item_label")}}
                {% if form.password.errors %}
                    {{ form.password(class="form_item_input bad_input")}}
                    {% for error in form.password.errors%}
                        <span class="bad_input_text">{{ error }}</span>
                    {% endfor %}
                {% else %}
                    {{ form.password(class="form_item_input")}}
                {% endif %}
            </div>
            <div class="form_item">
                {{ form.confirm_password.label(class="form_item_label")}}
                {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form_item_input bad_input")}}
                    {% for error in form.confirm_password.errors%}
                        <span class="bad_input_text">{{ error }}</span>
                    {% endfor %}
                {% else %}
                    {{ form.confirm_password(class="form_item_input")}}
                {% endif %}

            </div>
            <div class="form_item">
                {{ form.submit(class="form_item_input submit")}}
            </div>
        </fieldset>
    </form>
    <div class="hint">
        <span>Already have an account?</span>
        <a href="{{url_for("users.login")}}"> Sign in </a>
    </div>
{% endblock %}

flaskblog/templates/request.html
{% extends 'layout.html' %}
{% block content %}
    <form method="POST" action="" class="form">
        {{ form.hidden_tag() }}
        <fieldset>
            <legend>Enter an email</legend>
            <div class="form_item">
                {{ form.email.label(class="form_item_label")}}
                {% if form.email.errors %}
                    {{ form.email(class="form_item_input bad_input")}}
                    {% for error in form.email.errors%}
                        <span class="bad_input_text">{{ error }}</span>
                    {% endfor %}
                {% else %}
                    {{ form.email(class="form_item_input")}}
                {% endif %}
            </div>

            <div class="form_item">
                {{ form.submit(class="form_item_input submit")}}
            </div>
        </fieldset>
    </form>
{% endblock %}

flaskblog/templates/reset_password.html
{% extends 'layout.html' %}
{% block content %}
    <form method="POST" action="" class="form">
        {{ form.hidden_tag() }}
        <fieldset>
            <legend>Enter a new password</legend>
            <div class="form_item">
                {{ form.password.label(class="form_item_label")}}
                {% if form.password.errors %}
                    {{ form.password(class="form_item_input bad_input")}}
                    {% for error in form.password.errors%}
                        <span class="bad_input_text">{{ error }}</span>
                    {% endfor %}
                {% else %}
                    {{ form.password(class="form_item_input")}}
                {% endif %}
            </div>

            <div class="form_item">
                {{ form.confirm_password.label(class="form_item_label")}}
                {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form_item_input bad_input")}}
                    {% for error in form.confirm_password.errors%}
                        <span class="bad_input_text">{{ error }}</span>
                    {% endfor %}
                {% else %}
                    {{ form.confirm_password    (class="form_item_input")}}
                {% endif %}
            </div>

            <div class="form_item">
                {{ form.submit(class="form_item_input submit")}}
            </div>
        </fieldset>
    </form>
{% endblock %}

flaskblog/templates/user_posts.html
{% extends 'layout.html' %}
{% block content %}
    {% for post in posts.items %}
        <div class="post">
            <a class="name" href="{{ url_for('user_posts', username=post.author.username)}}"><img src="{{ url_for('static', filename="profile_pictures/" + post.author.img)}}" alt="Posts author image." class="article_img"></a>
            <div class="content">
                <div class="metadata">
                    <p><a class="name" href="{{ url_for('users.user_posts', username=post.author.username)}}">{{ post.author.username}}</a></p>
                    <p class="date">{{post.posted_date.strftime("%a %m %Y")}}</p>
                </div>
                <h2><a href="{{url_for('posts.post', post_id = post.id)}}">{{post.title}}</a></h2>
                <p>{{post.content}}</p>
            </div>
        </div>
    {% endfor %}
    <div class="pagination">
    {%- for page in posts.iter_pages(left_edge=1,right_edge=1, left_current=1, right_current=2) %}
        {% if page != None %}
            {% if page == posts.page %}
                <a href="{{ url_for("users.user_posts", page=page, username=posts.query.first().author.username) }}" class="pagination_item active" >{{ page }}</a>
            {% else %}
                <a href="{{ url_for("users.user_posts", page=page, username=posts.query.first().author.username) }}" class="pagination_item" >{{ page }}</a>
            {% endif %}
        {% else %}
            <a class="pagination_item" >...</a>
        {% endif %}
    {% endfor %}
    </div>
{% endblock content%}